# Generated by Django 4.1.13 on 2025-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_salesitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('KCB', 'KCB'), ('M-PESA', 'M-PESA'), ('CASH', 'CASH')], default='mpesa', max_length=10),
            preserve_default=False,
        ),
    ]
